### ISSUE TITLE
Google Maps MarkerClusterer should be configurable

### ISSUE THREAD

**Issue by ayastreb** [ayastreb/jekyll-maps#10]
As a user I should be able to enable/disable marker clustering and configure grid size, e.g.:
```yaml
maps:
  google:
    marker_clusterer:
      enabled: true
      grid_size: 25
```
