### ISSUE TITLE
Configurable Google Maps options with defaults

### ISSUE THREAD

**Issue by ayastreb** [ayastreb/jekyll-maps#12]
As a user I should be able to configure map [options](https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapOptions)

Options can be set globally via `_config.yml`:
```yaml
maps:
  google:
    options:
      disableDefaultUI: false
      scrollwheel: false
```

or it can be set from tag:
```
{% google_map on_page zoom:10 %}
```
