### ISSUE TITLE
Error: undefined method `each_value'.. Did you mean? each_slice

### ISSUE THREAD

**Issue by AndyClifton** [ayastreb/jekyll-maps#48]
I have installed in this using the process set out in the readme.

I have confirmed that I can generate a map directly, using e.g.,

    {% google_map latitude="48.8587741" longitude="2.2074741" marker_title="My Location" marker_img="/img.jpg" marker_url="/my-location.html" %}

I'm  now trying to read in files in a yml or JSON file. Using the example in the readme, I create a data file (`_data/map.yml`) with this content:

```
- title: Paris
  url: http://google.fr
  location:
    latitude: 48.8587741
    longitude: 2.2074741

- title: Madrid
  url: http://google.es
  location:
    latitude: 40.4378698
    longitude: -3.8196204
```

I then try to call it from a post, `map.md` following the example given in the Readme:

```
    {% google_map src="_data/map.yml" %}
```

Which unfortunately gives me this error: 

```
Liquid Exception: undefined method `each_value' for [{"title"=>"Paris", "url"=>"http://google.fr", "location"=>{"latitude"=>48.8587741, "longitude"=>2.2074741}}, {"title"=>"Madrid", "url"=>"http://google.es", "location"=>{"latitude"=>40.4378698, "longitude"=>-3.8196204}}]:Array Did you mean? each_slice in /blah/blah/map.md
```

All suggestions welcome!
