### ISSUE TITLE
Configurable Google Maps API key

### ISSUE THREAD

**Issue by ayastreb** [ayastreb/jekyll-maps#8]
As a user I should be able to set Google Maps API key from Jekyl config, e.g.
```yaml
maps:
  google:
    api_key: <-- MY_API_KEY_HERE -->
```
The API key from the config should be inserted in the script load tag.
